<?php
foreach ($posts as $post): ?>
<li class="post">
<h3>
<i class="fa fa-hand-o-right"></i>&nbsp;
<a href="show_post.php?id=<?= $post['Id'] ?>" title="Consulter l'article">
<?= $post['Title'] ?>
</a>
</h3>
<article>
<?= $post['Contents'] ?> 
<?= $post['LastName'] ?>
</article>
<small>
Rédigé par <?= $post['FirstName'] ?> <?= $post[
    'LastName'] ?>
    le <?= $post['CreationTimestamp'] ?>
</small>
</li>
<?php endforeach; ?>



